---

- hosts: kafka_brokers
  vars:
    kafka_version: "0.10.0.0"
    scala_version: "2.11"
    kafka_name: "kafka_{{ scala_version }}-{{ kafka_version }}"
    kafka_root: "/opt/software"
    kafka_home: "{{ kafka_root }}/{{ kafka_name }}"
    kafka_src: "http://www-eu.apache.org/dist/kafka/{{ kafka_version }}/{{ kafka_name }}.tgz"
  tasks:
    - name: make sure kafka is not installed
      stat:
        path: '{{ kafka_home }}/bin/kafka-server-start.sh'
      register: kafka_installed
    - debug:
        msg: '{{ kafka_name }} already installed, abort'
      when: kafka_installed["stat"]["exists"]
    - meta: end_play
      when: kafka_installed["stat"]["exists"]
    - name: install OpenJDK
      become: yes
      yum: 
        name=java-1.8.0-openjdk-headless.x86_64 
        state=present
    - name: create folder {{ kafka_root }} (if missing)
      become: yes
      file:
        path: '{{ kafka_root }}'
        state: directory
    - name: download and unpack Kafka
      become: yes
      unarchive:
        src: '{{ kafka_src }}'
        dest: '{{ kafka_root }}'
        remote_src: yes
    - name: deploy Kafka configuration file
      become: yes
      copy:
        src: server.properties
        dest: '{{ kafka_home }}/config/server.properties'
    - name: copy service files
      become: yes
      template:
        src: '{{ item }}.j2'
        dest: /usr/lib/systemd/system/{{ item }}
        force: yes
      with_items:
        - kafka.service
        - zookeeper.service
    - name: Reload systemctl modules
      become: yes
      command: systemctl daemon-reload
