---

- hosts: kafka_brokers
  tasks:
    - name: Make sure that the service files are installed
      stat:
        path: /usr/lib/systemd/system/{{ item }}
      with_items:
        - kafka.service
        - zookeeper.service
      register: kafka_present

    - name: Services not installed, abort play
      meta: end_play
      when: 
        - not kafka_present["results"][0]["stat"]["exists"]
        - not kafka_present["results"][1]["stat"]["exists"]

    - name: Run services
      become: yes
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - zookeeper
        - kafka
      when: 
        - kafka_present["results"][0]["stat"]["exists"]
        - kafka_present["results"][1]["stat"]["exists"]
